spring:
  datasource:
    username: root
    password: 123456
    url: # TODO
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.96.15.21
    port: 6379
    database: 0
    password: 123456